"""test_config_io.py — clean rewrite, backups, restore, scaffold.

All tests use tempfile dirs ONLY. NO test touches ~/.config/opencode/oh-my-openagent.jsonc.
DESIGN §config_io.py / §Verification check #7 (config I/O half).
"""
from __future__ import annotations

import glob
import os
import re
import stat
import tempfile
import time

import pytest

from omodel.config_io import (
    BackupInfo,
    ConfigParseError,
    _value_span,
    diff_text,
    list_backups,
    load_config,
    render,
    restore,
    save,
    serialize,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_file(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def _read_file(path: str) -> str:
    with open(path, encoding="utf-8") as f:
        return f.read()


# Realistic comment-dense config (simulates the user's live file before first oModel save)
ORIGINAL_JSONC = """\
// hand-curated palette — oModel will clean this on first save
{
  "$schema": "https://raw.githubusercontent.com/code-yeongyu/oh-my-openagent/dev/assets/oh-my-opencode.schema.json",
  "agents": {
    "sisyphus": {
      "model": "opencode/claude-opus-4-7"
      // "model": "moonshotai-cn/kimi-k2.5"
      // "model": "openai/gpt-5.5"
    }
  },
  "categories": {},
  "team_mode": false,
  "experimental": {"featureX": true},
  "claude_code": {
    "enabled": true
    // "skills": false
  }
}
"""

# Minimal config with non-model sections
MINIMAL_CONFIG = {
    "$schema": "https://raw.githubusercontent.com/code-yeongyu/oh-my-openagent/dev/assets/oh-my-opencode.schema.json",
    "agents": {
        "sisyphus": {"model": "opencode/claude-opus-4-7"}
    },
    "categories": {},
    "team_mode": False,
    "experimental": {"featureX": True},
    "claude_code": {"enabled": True},
}


# ---------------------------------------------------------------------------
# serialize()
# ---------------------------------------------------------------------------

class TestSerialize:

    def test_header_line(self):
        """First line is exactly the oModel header comment."""
        text = serialize(MINIMAL_CONFIG)
        assert text.startswith("// Generated by oModel — edit via `omodel`\n")

    def test_schema_forced_to_position_0(self):
        """$schema appears as the first JSON key even if it was later in the dict."""
        cfg = {"agents": {}, "categories": {}, "$schema": "https://example.com/schema"}
        text = serialize(cfg)
        body = text[text.index("\n") + 1:]
        import json
        parsed = json.loads(body)
        keys = list(parsed.keys())
        assert keys[0] == "$schema", f"$schema must be first key; got {keys}"

    def test_single_trailing_newline(self):
        """Serialized text ends with exactly one newline."""
        text = serialize(MINIMAL_CONFIG)
        assert text.endswith("\n")
        assert not text.endswith("\n\n")

    def test_no_comments_emitted(self):
        """json.dumps cannot emit comments — none should appear in output."""
        text = serialize(MINIMAL_CONFIG)
        lines = text.splitlines()
        # Only the header line starts with //
        comment_lines = [line for line in lines[1:] if line.strip().startswith("//")]
        assert comment_lines == [], f"Unexpected comment lines: {comment_lines}"

    def test_non_model_sections_preserved(self):
        """team_mode, experimental, claude_code pass through by value."""
        text = serialize(MINIMAL_CONFIG)
        import json
        body = text[text.index("\n") + 1:]
        parsed = json.loads(body)
        assert parsed["team_mode"] is False
        assert parsed["experimental"] == {"featureX": True}
        assert parsed["claude_code"] == {"enabled": True}

    def test_agents_model_preserved(self):
        """The agents.sisyphus.model value is preserved exactly."""
        text = serialize(MINIMAL_CONFIG)
        import json
        body = text[text.index("\n") + 1:]
        parsed = json.loads(body)
        assert parsed["agents"]["sisyphus"]["model"] == "opencode/claude-opus-4-7"

    def test_schema_absent_when_not_in_cfg(self):
        cfg = {"agents": {}, "categories": {}}
        text = serialize(cfg)
        assert "$schema" not in text


# ---------------------------------------------------------------------------
# save() — backup sequence and clean rewrite
# ---------------------------------------------------------------------------

class TestSave:

    def test_first_save_creates_original_jsonc(self):
        """First save → .backup/original.jsonc created verbatim (comments intact)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            result = save(MINIMAL_CONFIG, cfg_path)

            assert result.changed is True
            assert result.original_created is True
            orig = os.path.join(tmpdir, ".backup", "original.jsonc")
            assert os.path.exists(orig)
            # Must be VERBATIM byte copy — comments intact
            assert _read_file(orig) == ORIGINAL_JSONC

    def test_first_save_creates_timestamped_snapshot(self):
        """First save → a timestamped .backup/<ts>.jsonc snapshot."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            result = save(MINIMAL_CONFIG, cfg_path)

            assert result.backup is not None
            assert os.path.exists(result.backup)
            ts_name = os.path.basename(result.backup)
            # Name matches YYYYMMDD-HHMMSS.mmm.jsonc pattern
            assert re.match(r"\d{8}-\d{6}\.\d{3}\.jsonc$", ts_name), (
                f"Unexpected snapshot name: {ts_name}"
            )

    def test_second_save_adds_second_snapshot(self):
        """Second save → original.jsonc unchanged, second timestamped snapshot created."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)
            # Change model to trigger a second save
            cfg2 = dict(MINIMAL_CONFIG)
            cfg2["agents"] = {"sisyphus": {"model": "deepseek/deepseek-v4-pro"}}
            time.sleep(0.01)  # ensure different timestamp
            result2 = save(cfg2, cfg_path)

            backup_dir = os.path.join(tmpdir, ".backup")
            timestamped = sorted(glob.glob(os.path.join(backup_dir, "[0-9]*.jsonc")))
            assert len(timestamped) == 2, (
                f"Expected 2 timestamped snapshots, got {len(timestamped)}"
            )
            assert result2.original_created is False, "original.jsonc must not be recreated"

    def test_original_never_overwritten(self):
        """original.jsonc is created once and never overwritten on subsequent saves."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)
            orig_path = os.path.join(tmpdir, ".backup", "original.jsonc")
            mtime_after_first = os.path.getmtime(orig_path)

            cfg2 = dict(MINIMAL_CONFIG)
            cfg2["agents"] = {"sisyphus": {"model": "moonshotai-cn/kimi-k2.5"}}
            time.sleep(0.02)
            save(cfg2, cfg_path)

            mtime_after_second = os.path.getmtime(orig_path)
            assert mtime_after_first == mtime_after_second, "original.jsonc must not be modified"

    def test_no_change_returns_not_changed(self):
        """Saving the same content → SaveResult(changed=False), no new snapshot."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            # Write what serialize would produce so there's no diff
            _write_file(cfg_path, serialize(MINIMAL_CONFIG))

            result = save(MINIMAL_CONFIG, cfg_path)

            assert result.changed is False
            assert result.backup is None

    def test_atomic_write(self):
        """The config file is updated atomically (temp+rename) with the text-preserving render."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)

            # After save, the on-disk file is render(cfg, prior-on-disk): only agents/categories
            # rewritten, everything else (incl. comments) spliced in place.
            written = _read_file(cfg_path)
            assert written == render(MINIMAL_CONFIG, ORIGINAL_JSONC)

    def test_save_drops_inside_palette(self):
        """First save drops the commented palette INSIDE agents/categories (decision #13) — those
        spans are rewritten clean (the active model alone remains)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)

            written = _read_file(cfg_path)
            # The sisyphus palette alternatives lived INSIDE agents → gone.
            assert "moonshotai-cn/kimi-k2.5" not in written
            assert "openai/gpt-5.5" not in written
            # The one active model remains.
            assert "opencode/claude-opus-4-7" in written

    def test_save_preserves_outside_comments(self):
        """Comments / commented-out config OUTSIDE agents/categories survive verbatim — omodel
        manages only those two keys (decision #13, narrowed)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            assert "//" in ORIGINAL_JSONC, "Test fixture must have comments"

            save(MINIMAL_CONFIG, cfg_path)
            written = _read_file(cfg_path)

            # The top banner comment and the inline comment inside the non-model `claude_code`
            # block are OUTSIDE agents/categories → preserved.
            assert "// hand-curated palette" in written
            assert '// "skills": false' in written

            # And the original remains pinned verbatim regardless.
            orig_path = os.path.join(tmpdir, ".backup", "original.jsonc")
            assert _read_file(orig_path) == ORIGINAL_JSONC

    def test_save_when_config_never_existed(self):
        """save() to a path with no on-disk file at all (the `old_text is None` branch):
        render() falls back to serialize(cfg) since there's no base text to splice into, the
        timestamped snapshot is created but EMPTY (nothing existed to snapshot verbatim), and
        original.jsonc is NOT created — there is nothing on disk to pin as "original". This is
        the intended behavior (a first-ever save has no prior state to preserve), not a gap."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            # Deliberately no file written at cfg_path — this is a first-ever save.

            result = save(MINIMAL_CONFIG, cfg_path)

            assert result.changed is True
            assert result.original_created is False
            assert _read_file(cfg_path) == serialize(MINIMAL_CONFIG)

            assert result.backup is not None
            assert os.path.exists(result.backup)
            assert _read_file(result.backup) == ""

            orig_path = os.path.join(tmpdir, ".backup", "original.jsonc")
            assert not os.path.exists(orig_path)


# ---------------------------------------------------------------------------
# Prune logic
# ---------------------------------------------------------------------------

class TestPruneSnapshots:

    def test_prune_keeps_newest_20(self):
        """After >20 saves, only the newest 20 timestamped snapshots remain."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            # First save (creates original.jsonc)
            save(MINIMAL_CONFIG, cfg_path)

            # 21 more saves with distinct content
            for i in range(21):
                cfg = dict(MINIMAL_CONFIG)
                cfg["agents"] = {"sisyphus": {"model": f"opencode/model-{i}"}}
                time.sleep(0.002)  # force distinct timestamps
                save(cfg, cfg_path)

            backup_dir = os.path.join(tmpdir, ".backup")
            timestamped = glob.glob(os.path.join(backup_dir, "[0-9]*.jsonc"))
            assert len(timestamped) <= 20, (
                f"Expected ≤20 timestamped snapshots, got {len(timestamped)}"
            )

    def test_prune_never_removes_original(self):
        """original.jsonc is NEVER pruned regardless of snapshot count."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)
            for i in range(25):
                cfg = dict(MINIMAL_CONFIG)
                cfg["agents"] = {"sisyphus": {"model": f"opencode/model-{i}"}}
                time.sleep(0.002)
                save(cfg, cfg_path)

            orig_path = os.path.join(tmpdir, ".backup", "original.jsonc")
            assert os.path.exists(orig_path), "original.jsonc must never be pruned"


# ---------------------------------------------------------------------------
# list_backups()
# ---------------------------------------------------------------------------

class TestListBackups:

    def _do_two_saves(self, tmpdir: str) -> str:
        """Helper: write original, save once, save again. Returns config path."""
        cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
        _write_file(cfg_path, ORIGINAL_JSONC)

        save(MINIMAL_CONFIG, cfg_path)

        cfg2 = dict(MINIMAL_CONFIG)
        cfg2["agents"] = {"sisyphus": {"model": "deepseek/deepseek-v4-pro"}}
        time.sleep(0.01)
        save(cfg2, cfg_path)
        return cfg_path

    def test_list_backups_original_first(self):
        """original.jsonc is always the first entry when present."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = self._do_two_saves(tmpdir)
            result = list_backups(cfg_path)
            assert result[0].is_original is True
            assert result[0].name == "original.jsonc"

    def test_list_backups_newest_first(self):
        """Timestamped entries are listed newest-first."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = self._do_two_saves(tmpdir)
            result = list_backups(cfg_path)
            ts_entries = [b for b in result if not b.is_original]
            if len(ts_entries) >= 2:
                names = [b.name for b in ts_entries]
                assert names == sorted(names, reverse=True), (
                    f"Entries not newest-first: {names}"
                )

    def test_list_backups_entry_shape(self):
        """Each BackupInfo has name, path, is_original, size."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = self._do_two_saves(tmpdir)
            result = list_backups(cfg_path)
            for bi in result:
                assert isinstance(bi, BackupInfo)
                assert isinstance(bi.name, str)
                assert isinstance(bi.path, str)
                assert isinstance(bi.is_original, bool)
                assert isinstance(bi.size, int)

    def test_list_backups_max_10_timestamped(self):
        """list_backups returns at most 10 timestamped snapshots (+ optional original)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)
            save(MINIMAL_CONFIG, cfg_path)
            for i in range(15):
                cfg = dict(MINIMAL_CONFIG)
                cfg["agents"] = {"sisyphus": {"model": f"opencode/model-{i}"}}
                time.sleep(0.002)
                save(cfg, cfg_path)
            result = list_backups(cfg_path)
            ts_only = [b for b in result if not b.is_original]
            assert len(ts_only) <= 10

    def test_list_backups_empty_when_no_backups(self):
        """No saves yet → list_backups returns []."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            result = list_backups(cfg_path)
            assert result == []


# ---------------------------------------------------------------------------
# restore()
# ---------------------------------------------------------------------------

class TestRestore:

    def test_restore_round_trip(self):
        """Restore original.jsonc → config becomes the original content."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)  # rewrites config, creates original.jsonc

            # Restore original
            restore(cfg_path, "original.jsonc")

            restored = _read_file(cfg_path)
            assert restored == ORIGINAL_JSONC, "Restored content must match original verbatim"

    def test_restore_snapshots_current_first(self):
        """restore() snapshots the CURRENT file before overwriting (restore is undoable)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)

            save(MINIMAL_CONFIG, cfg_path)
            content_before_restore = _read_file(cfg_path)

            backup_dir = os.path.join(tmpdir, ".backup")
            ts_before = set(glob.glob(os.path.join(backup_dir, "[0-9]*.jsonc")))

            time.sleep(0.01)
            restore(cfg_path, "original.jsonc")

            ts_after = set(glob.glob(os.path.join(backup_dir, "[0-9]*.jsonc")))
            new_snaps = ts_after - ts_before
            assert len(new_snaps) == 1, "restore() must create exactly one new snapshot"
            # The new snapshot contains what was the live file before restore
            snap_content = _read_file(next(iter(new_snaps)))
            assert snap_content == content_before_restore


# ---------------------------------------------------------------------------
# load_config() scaffolding
# ---------------------------------------------------------------------------

class TestLoadConfig:

    def test_scaffold_when_missing(self):
        """Missing config → scaffold the UNIFIED default and return a dict. omo 4.19.3+ reads
        agents/categories from `"[opencode]"`, so a from-scratch scaffold must land there; a
        top-level pair would be accepted, saved, and then silently outranked."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "subdir", "oh-my-openagent.jsonc")
            cfg, resolved = load_config(cfg_path)
            assert os.path.exists(resolved)
            assert isinstance(cfg, dict)
            assert "agents" not in cfg
            assert "agents" in cfg["[opencode]"]
            assert "categories" in cfg["[opencode]"]

    def test_existing_config_loaded(self):
        """Existing config is loaded as a dict."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            # Write a comment-free config that json5 can parse
            _write_file(cfg_path, '{"agents": {"sisyphus": {"model": "opencode/claude-opus-4-7"}}, "categories": {}, "team_mode": false}\n')
            cfg, _resolved = load_config(cfg_path)
            assert cfg["agents"]["sisyphus"]["model"] == "opencode/claude-opus-4-7"
            assert cfg["team_mode"] is False

    def test_relative_missing_path_scaffolds_via_cwd(self, monkeypatch, tmp_path):
        """A bare RELATIVE filename that doesn't exist yet must not crash: os.path.dirname of a
        bare filename (no directory component) is "" — load_config resolves the parent via
        os.path.abspath before makedirs so this scaffolds cleanly instead of raising
        FileNotFoundError."""
        monkeypatch.chdir(tmp_path)
        cfg, resolved = load_config("rel-missing.jsonc")
        assert os.path.exists(resolved)
        assert isinstance(cfg, dict)
        assert "agents" in cfg["[opencode]"]
        assert "categories" in cfg["[opencode]"]

    def test_malformed_config_raises_config_parse_error(self):
        """A JSONC syntax error raises ConfigParseError (not a raw json5 traceback), with the
        config path in the message — cli.py's --print / TUI-launch paths catch this narrow
        type to print a friendly message instead of letting the traceback escape."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, "{ this is not valid json ][")

            with pytest.raises(ConfigParseError) as exc_info:
                load_config(cfg_path)
            assert cfg_path in str(exc_info.value)


# ---------------------------------------------------------------------------
# diff_text()
# ---------------------------------------------------------------------------

class TestDiffText:

    def test_diff_text_nonempty_when_changed(self):
        """diff_text returns a non-empty string when config differs from disk."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)
            diff = diff_text(MINIMAL_CONFIG, cfg_path)
            assert diff != ""

    def test_diff_text_empty_when_same(self):
        """diff_text returns empty string when config matches serialize output."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, serialize(MINIMAL_CONFIG))
            diff = diff_text(MINIMAL_CONFIG, cfg_path)
            assert diff == ""

    def test_diff_text_does_not_delete_outside_comments(self):
        """The confirm-modal diff must NOT show outside comments being removed — only
        agents/categories lines change."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)
            diff = diff_text(MINIMAL_CONFIG, cfg_path)
            # No '-' (removal) line that strips the outside claude_code comment.
            removed = [ln for ln in diff.splitlines() if ln.startswith("-") and not ln.startswith("---")]
            assert not any('"skills": false' in ln for ln in removed)
            assert not any("hand-curated palette" in ln for ln in removed)


# ---------------------------------------------------------------------------
# render() — text-preserving splice (only agents/categories rewritten)
# ---------------------------------------------------------------------------

# Stress fixture: a fakeout string carrying `{`, `}`, `"agents":`, and `//` (the span scanner
# must not be fooled), a commented palette INSIDE both agents and categories, a parked
# commented-out top-level block, and an inline /* */ block comment in a non-model section.
RICH_JSONC = """\
// top banner the user wrote — keep me
{
  "$schema": "https://example.com/s.json",
  "note": "has { braces } and \\"agents\\": fakeout and // slashes",
  "agents": {
    "sisyphus": {
      "model": "opencode/claude-opus-4-7"
      // "model": "openai/gpt-5.5"
    }
  },
  "categories": {
    "summarizer": {
      "model": "opencode/gpt-5.5-mini"
      // "model": "deepseek/deepseek-v4"
    }
  },
  "team_mode": false,
  // parked top-level config the user wants to keep:
  // "team_mode_overrides": { "x": 1 },
  "weird": "trailing } brace and \\" quote",
  "claude_code": { "enabled": true /* inline block */ }
}
"""

RICH_CFG = {
    "$schema": "https://example.com/s.json",
    "note": 'has { braces } and "agents": fakeout and // slashes',
    "agents": {"sisyphus": {"model": "deepseek/deepseek-v4-pro"}},
    "categories": {"summarizer": {"model": "opencode/gpt-5.5"}},
    "team_mode": False,
    "weird": 'trailing } brace and " quote',
    "claude_code": {"enabled": True},
}


class TestRender:

    def test_rewrites_agents_and_categories(self):
        out = render(RICH_CFG, RICH_JSONC)
        assert '"model": "deepseek/deepseek-v4-pro"' in out
        assert '"model": "opencode/gpt-5.5"' in out

    def test_drops_palette_inside_agents_and_categories(self):
        out = render(RICH_CFG, RICH_JSONC)
        assert '// "model": "openai/gpt-5.5"' not in out      # agents palette
        assert '// "model": "deepseek/deepseek-v4"' not in out  # categories palette

    def test_preserves_outside_comments_and_config(self):
        out = render(RICH_CFG, RICH_JSONC)
        assert "// top banner the user wrote" in out
        assert '// "team_mode_overrides": { "x": 1 }' in out   # parked top-level block
        assert "/* inline block */" in out                     # inline comment in claude_code

    def test_fakeout_string_not_mistaken_for_member(self):
        """A string value containing `{ }`, `"agents":`, and `//` must be preserved verbatim and
        must not confuse the span scan."""
        out = render(RICH_CFG, RICH_JSONC)
        # Verbatim in the raw text (escaped quotes intact); the decoded value is checked in
        # test_result_parses_and_matches_active_structure.
        assert "has { braces } and" in out
        assert "fakeout and // slashes" in out
        assert "trailing } brace and" in out

    def test_result_parses_and_matches_active_structure(self):
        import json5
        out = render(RICH_CFG, RICH_JSONC)
        parsed = json5.loads(out)
        assert parsed["agents"] == {"sisyphus": {"model": "deepseek/deepseek-v4-pro"}}
        assert parsed["categories"] == {"summarizer": {"model": "opencode/gpt-5.5"}}
        assert parsed["note"] == RICH_CFG["note"]
        assert parsed["weird"] == RICH_CFG["weird"]
        assert parsed["team_mode"] is False
        assert parsed["claude_code"] == {"enabled": True}

    def test_idempotent(self):
        """Rendering already-rendered output reproduces it byte-for-byte (so an unchanged save is
        'nothing to save')."""
        out = render(RICH_CFG, RICH_JSONC)
        assert render(RICH_CFG, out) == out

    def test_empty_value_objects_unchanged(self):
        """`"agents": {}` / `"categories": {}` stay inline `{}` when empty (idempotent splice)."""
        base = (
            '{\n  "$schema": "x",\n  "agents": {},\n  "categories": {},\n'
            '  // keep\n  "team_mode": false\n}\n'
        )
        cfg = {"$schema": "x", "agents": {}, "categories": {}, "team_mode": False}
        out = render(cfg, base)
        assert out == base                       # nothing to change → byte-identical
        assert "// keep" in out

    def test_preserves_four_space_indent_alignment(self):
        """A 4-space-indented file keeps its key indent on the spliced block's closing brace."""
        base = (
            "{\n"
            '    "agents": {\n'
            '        "sisyphus": {\n'
            '            "model": "old"\n'
            "        }\n"
            "    },\n"
            '    "categories": {}\n'
            "}\n"
        )
        cfg = {"agents": {"sisyphus": {"model": "new"}}, "categories": {}}
        out = render(cfg, base)
        assert '"model": "new"' in out
        # The agents object's closing brace aligns under the 4-space key indent.
        assert "\n    }," in out
        import json5
        assert json5.loads(out)["agents"]["sisyphus"]["model"] == "new"

    def test_fallback_to_serialize_when_no_base(self):
        cfg = {"agents": {}, "categories": {}}
        assert render(cfg, "") == serialize(cfg)
        assert render(cfg, None) == serialize(cfg)
        assert render(cfg, "   \n  ") == serialize(cfg)

    def test_fallback_when_absent_key_has_something_to_write(self):
        """A key that isn't a direct root member has nowhere to be spliced, so a NON-EMPTY value
        forces the clean rewrite — that is the only way to express the change."""
        cfg = {"agents": {}, "categories": {"deep": {"model": "openai/gpt-5.5"}},
               "team_mode": False}
        base_no_categories = '{\n  "agents": {},\n  "team_mode": false\n}\n'
        assert render(cfg, base_no_categories) == serialize(cfg)

    def test_absent_but_empty_key_leaves_the_file_alone(self):
        """...whereas an absent key that is ALSO empty has nothing to express, so the file keeps
        its comments and formatting instead of being rewritten to add `"categories": {}`. The
        rewrite costs every comment in the document — on a unified config that is omo's config,
        not just omodel's — so it is reserved for when splicing genuinely cannot work."""
        cfg = {"agents": {}, "categories": {}, "team_mode": False}
        base = '// hi\n{\n  "agents": {},\n  "team_mode": false\n}\n'
        out = render(cfg, base)
        assert out == base
        assert "// hi" in out


# ---------------------------------------------------------------------------
# _value_span() — the JSONC span scanner render() relies on
# ---------------------------------------------------------------------------

class TestTopLevelValueSpan:

    def test_finds_agents_and_categories(self):
        a = _value_span(RICH_JSONC, "agents")
        c = _value_span(RICH_JSONC, "categories")
        assert a is not None and c is not None
        agents_text = RICH_JSONC[a[0]:a[1]]
        categories_text = RICH_JSONC[c[0]:c[1]]
        assert agents_text.startswith("{") and agents_text.endswith("}")
        assert "sisyphus" in agents_text
        assert "summarizer" in categories_text
        # categories comes after agents in the file
        assert c[0] > a[1]

    def test_fakeout_string_does_not_match(self):
        """The real `agents` span (with sisyphus) is found, not the `"agents":` inside `note`."""
        a = _value_span(RICH_JSONC, "agents")
        assert "sisyphus" in RICH_JSONC[a[0]:a[1]]

    def test_nested_key_is_not_a_root_member(self):
        assert _value_span(RICH_JSONC, "model") is None
        assert _value_span(RICH_JSONC, "sisyphus") is None

    def test_absent_key_returns_none(self):
        assert _value_span(RICH_JSONC, "does_not_exist") is None

    def test_no_root_object_returns_none(self):
        assert _value_span("// just a comment\n[1, 2, 3]\n", "agents") is None


# ---------------------------------------------------------------------------
# save() keeps the file's identity — BOM, line endings, permission bits, a symlink
# ---------------------------------------------------------------------------

# A unified-scope config with comments in the three places that must survive: above the
# document, inside `[opencode]` but outside agents/categories, and inside another top-level key.
IDENTITY_SEED = """\
// hand-curated banner — outside agents/categories, must survive
{
  "team_mode": true,
  "[opencode]": {
    // a note about the agents below
    "agents": {
      "sisyphus": {"model": "opencode/glm-5"}
    },
    "categories": {}
  },
  "claude_code": {
    // keep me too
    "enabled": false
  }
}
"""
IDENTITY_COMMENTS = ("// hand-curated banner", "// a note about the agents below", "// keep me too")
BOM = "\ufeff"


def _write_bytes(path: str, data: bytes) -> None:
    with open(path, "wb") as f:
        f.write(data)


def _read_bytes(path: str) -> bytes:
    with open(path, "rb") as f:
        return f.read()


def _set_sisyphus(cfg_path: str, model: str = "opencode/glm-9"):
    """Load, change one model, save — the smallest edit `omodel set` performs."""
    cfg, resolved = load_config(cfg_path)
    cfg["[opencode]"]["agents"]["sisyphus"]["model"] = model
    return save(cfg, resolved)


class TestSaveKeepsFileIdentity:
    """`save` rewrites two value spans and leaves the rest of the file — its bytes AND what kind
    of file it is — as it found it. Each test here is a defect the 0.5.1 review/test pass found:
    a BOM cost every comment, CRLF became LF, 0644 became 0600, a symlink became a file."""

    def test_bom_prefixed_config_keeps_its_comments(self, tmp_path):
        """U+FEFF hid the root `{` from the span scanner, so both spans came back None and
        `render` fell back to the clean rewrite: one `set` and every comment — omo's own
        included — was gone. The BOM is trivia now, and is kept like any other byte."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_bytes(cfg_path, (BOM + IDENTITY_SEED).encode("utf-8"))

        _set_sisyphus(cfg_path)

        after = _read_bytes(cfg_path)
        assert after.startswith(b"\xef\xbb\xbf")
        for comment in IDENTITY_COMMENTS:
            assert comment.encode("utf-8") in after, comment
        assert b'"model": "opencode/glm-9"' in after

    def test_bom_and_bomless_saves_agree(self, tmp_path):
        """Control: the BOM is the ONLY difference between the two results."""
        bom_path = str(tmp_path / "with-bom" / "omo.jsonc")
        plain_path = str(tmp_path / "no-bom" / "omo.jsonc")
        _write_file(bom_path, BOM + IDENTITY_SEED)
        _write_file(plain_path, IDENTITY_SEED)

        _set_sisyphus(bom_path)
        _set_sisyphus(plain_path)

        assert _read_bytes(bom_path) == BOM.encode("utf-8") + _read_bytes(plain_path)

    def test_crlf_config_stays_crlf(self, tmp_path):
        """Read and written with `newline=""`, so the endings a Windows file arrives with are
        the endings it keeps; the rewrite used to flip every line of the file to LF."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_bytes(cfg_path, IDENTITY_SEED.replace("\n", "\r\n").encode("utf-8"))

        _set_sisyphus(cfg_path)

        after = _read_bytes(cfg_path)
        assert after.count(b"\r\n") == after.count(b"\n") > 5, "every line ending is CRLF"
        assert b'"model": "opencode/glm-9"' in after
        for comment in IDENTITY_COMMENTS:
            assert comment.encode("utf-8") in after, comment

    def test_crlf_preview_diff_lists_only_the_changed_lines(self, tmp_path):
        """`diff_text` compares with the file's own endings (else every line differed, while
        the preview claimed a one-line change) and renders with `\\n` — a `\\r` on every diff
        line is noise in the modal and in the `--json` payload."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_bytes(cfg_path, IDENTITY_SEED.replace("\n", "\r\n").encode("utf-8"))
        cfg, resolved = load_config(cfg_path)
        cfg["[opencode]"]["agents"]["sisyphus"]["model"] = "opencode/glm-9"

        diff = diff_text(cfg, resolved)

        assert "\r" not in diff
        changed = [ln for ln in diff.splitlines()
                   if ln[:1] in "+-" and not ln.startswith(("+++", "---"))]
        # One line out, three in: json.dumps expands the one-line object. Nothing else moves.
        assert len(changed) == 4, changed
        assert not any("team_mode" in ln or "keep me" in ln for ln in changed)

    def test_unchanged_crlf_config_is_a_no_op_save(self, tmp_path):
        """With the endings read verbatim, `render(cfg, on-disk) == on-disk` holds for an
        unchanged CRLF file — nothing is written, no backup slot is spent."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_bytes(cfg_path, IDENTITY_SEED.replace("\n", "\r\n").encode("utf-8"))
        cfg, resolved = load_config(cfg_path)
        assert save(cfg, resolved).changed is True  # canonicalizes the one-line agents object
        before = _read_bytes(cfg_path)
        # Still CRLF after that first save — HEAD passed the no-op half of this test only
        # because it had already flipped the whole file to LF.
        assert before.count(b"\r\n") == before.count(b"\n") > 5

        assert save(cfg, resolved).changed is False
        assert _read_bytes(cfg_path) == before

    @pytest.mark.skipif(os.name == "nt", reason="POSIX permission bits")
    def test_save_keeps_the_permission_bits(self, tmp_path):
        """The temp file's mode (0600, from the NamedTemporaryFile `save` used) rode the rename
        onto the config, silently retightening a 0644 file on its first save."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_file(cfg_path, IDENTITY_SEED)
        os.chmod(cfg_path, 0o640)

        _set_sisyphus(cfg_path)

        assert stat.S_IMODE(os.stat(cfg_path).st_mode) == 0o640

    @pytest.mark.skipif(os.name == "nt", reason="symlinks need a privilege on Windows")
    def test_save_writes_through_a_symlinked_config(self, tmp_path):
        """A dotfile manager (stow/chezmoi/yadm) points ~/.omo/omo.jsonc at a repo file.
        Renaming over the link replaced it with a detached regular file: the repo copy stayed on
        the old model and the next `stow` run would have clobbered the new one. The rename now
        lands on the file the link resolves to; `.backup/` stays beside the link, where the
        user pointed omodel."""
        real = tmp_path / "dotfiles" / "omo.jsonc"
        link_dir = tmp_path / "home" / ".omo"
        _write_file(str(real), IDENTITY_SEED)
        os.makedirs(str(link_dir))
        link = link_dir / "omo.jsonc"
        os.symlink(str(real), str(link))

        _set_sisyphus(str(link))

        assert os.path.islink(str(link))
        assert '"opencode/glm-9"' in real.read_text(encoding="utf-8")
        assert os.path.isdir(str(link_dir / ".backup"))
        assert not os.path.exists(str(tmp_path / "dotfiles" / ".backup"))
        assert not [n for n in os.listdir(str(tmp_path / "dotfiles")) if ".tmp" in n]

    def test_no_temp_file_is_left_behind(self, tmp_path):
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_file(cfg_path, IDENTITY_SEED)
        _set_sisyphus(cfg_path)
        assert not [n for n in os.listdir(str(tmp_path)) if ".tmp" in n]


class TestLoadConfigReportsUnreadablePaths:
    """`load_config` guarded the parse but not the open: a directory at the path (`--config
    ~/.omo`, one component short of the file) or an unreadable file escaped as a raw OSError
    traceback. Both are `ConfigReadError` now — a ConfigParseError, so every caller's friendly
    exit-1 handling covers them without knowing the difference."""

    def test_directory_at_the_path(self, tmp_path):
        from omodel.config_io import ConfigReadError
        with pytest.raises(ConfigReadError, match="could not read config at"):
            load_config(str(tmp_path))

    def test_it_is_a_config_parse_error(self, tmp_path):
        from omodel.config_io import ConfigReadError
        assert issubclass(ConfigReadError, ConfigParseError)
        with pytest.raises(ConfigParseError):
            load_config(str(tmp_path))

    @pytest.mark.skipif(os.name == "nt" or os.getuid() == 0, reason="needs POSIX, non-root")
    def test_unreadable_file(self, tmp_path):
        from omodel.config_io import ConfigReadError
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_file(cfg_path, IDENTITY_SEED)
        os.chmod(cfg_path, 0o000)
        try:
            with pytest.raises(ConfigReadError, match=re.escape(cfg_path)):
                load_config(cfg_path)
        finally:
            os.chmod(cfg_path, 0o644)

    def test_unwritable_scaffold_location(self, tmp_path):
        """A missing config is scaffolded; a path whose parent cannot be created (a FILE where
        a directory is needed) is the same class of failure on the write side."""
        from omodel.config_io import ConfigReadError
        blocker = tmp_path / "blocker"
        blocker.write_text("not a directory", encoding="utf-8")
        with pytest.raises(ConfigReadError, match="could not create config at"):
            load_config(str(blocker / "sub" / "omo.jsonc"))


class TestRestoreRefusesBeforeWriting:

    def test_unknown_backup_name_burns_no_snapshot(self):
        """A name that isn't in .backup/ used to take the safety snapshot first and raise
        after — one ring slot spent on the way to an error."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "oh-my-openagent.jsonc")
            _write_file(cfg_path, ORIGINAL_JSONC)
            save(MINIMAL_CONFIG, cfg_path)
            backup_dir = os.path.join(tmpdir, ".backup")
            before = sorted(os.listdir(backup_dir))
            live = _read_file(cfg_path)

            with pytest.raises(FileNotFoundError):
                restore(cfg_path, "nope.jsonc")

            assert sorted(os.listdir(backup_dir)) == before
            assert _read_file(cfg_path) == live


class TestMixedAndLegacyLineEndings:
    """The two edge cases the CRLF change opened (found by the diff review), pinned."""

    def test_preview_and_save_agree_on_a_mixed_endings_file(self, tmp_path):
        """One stray CRLF line outside the spans in an otherwise-LF file. `diff_text` used to
        normalize its inputs while `save` compared raw bytes — so with NO edit the preview said
        nothing changes and the write flipped the spliced block to CRLF (burning a backup
        slot; in the TUI it took the no-confirm "Nothing to save." path and wrote anyway).
        A spliced block now takes its own line's ending, and the two compare the same bytes."""
        cfg_path = str(tmp_path / "omo.jsonc")
        mixed = IDENTITY_SEED.replace('  "team_mode": true,\n', '  "team_mode": true,\r\n')
        _write_bytes(cfg_path, mixed.encode("utf-8"))
        cfg, resolved = load_config(cfg_path)
        assert save(cfg, resolved).changed is True  # canonicalizes the one-line agents object
        before = _read_bytes(cfg_path)
        assert before.count(b"\r\n") == 1, "the stray line is still the only CRLF one"

        assert diff_text(cfg, resolved) == ""
        assert save(cfg, resolved).changed is False
        assert _read_bytes(cfg_path) == before

    def test_spliced_block_takes_its_neighbours_ending(self, tmp_path):
        """Same file, a real edit: the block under `"agents":` stays LF like its own line, the
        stray CRLF line elsewhere stays CRLF, and the preview lists only the changed lines."""
        cfg_path = str(tmp_path / "omo.jsonc")
        mixed = IDENTITY_SEED.replace('  "team_mode": true,\n', '  "team_mode": true,\r\n')
        _write_bytes(cfg_path, mixed.encode("utf-8"))
        cfg, resolved = load_config(cfg_path)
        cfg["[opencode]"]["agents"]["sisyphus"]["model"] = "opencode/glm-9"

        diff = diff_text(cfg, resolved)
        save(cfg, resolved)

        after = _read_bytes(cfg_path)
        assert after.count(b"\r\n") == 1
        assert b'"model": "opencode/glm-9"\n' in after
        changed = [ln for ln in diff.splitlines()
                   if ln[:1] in "+-" and not ln.startswith(("+++", "---"))]
        assert len(changed) == 4, changed

    def test_classic_mac_cr_only_file_keeps_its_comments(self, tmp_path):
        """With reads no longer translating `\\r` to `\\n`, a `//` comment that ended only at
        `\\n` swallowed a CR-only document — both spans None, clean rewrite, comments gone.
        Line comments now end at either character, and the file stays CR-only."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_bytes(cfg_path, IDENTITY_SEED.replace("\n", "\r").encode("utf-8"))

        _set_sisyphus(cfg_path)

        after = _read_bytes(cfg_path)
        assert b"\n" not in after, "still CR-only"
        assert after.count(b"\r") > 5
        for comment in IDENTITY_COMMENTS:
            assert comment.encode("utf-8") in after, comment
        assert b'"model": "opencode/glm-9"' in after
        # …and it is stable: the block was indented from its own line, so a re-save is a no-op.
        cfg, resolved = load_config(cfg_path)
        assert save(cfg, resolved).changed is False


class TestLeadingWhitespaceJson5Accepts:
    """The BOM was one character of a class: json5 also reads NBSP, U+2028/2029, vertical tab,
    form feed and the U+2000 family as whitespace, and each hid the root `{` from the span
    scanner exactly as the BOM did (diff review). `str.isspace` covers all of them."""

    BODY = '{\n  "[opencode]": {\n    "agents": {"a": {}},\n    "categories": {}\n  }\n}\n'

    @pytest.mark.parametrize("ws", ["\ufeff", "\u00a0", "\u2028", "\u2029", "\x0b", "\x0c", "\u2000"],
                             ids=["bom", "nbsp", "u2028", "u2029", "vt", "ff", "u2000"])
    def test_span_scanner_sees_past_it(self, ws):
        from omodel.config_io import OPENCODE_BLOCK, _span_for_path
        assert _span_for_path(ws + self.BODY, [OPENCODE_BLOCK, "agents"]) is not None
        assert _span_for_path(ws + "\n" + self.BODY, [OPENCODE_BLOCK, "agents"]) is not None

    def test_nbsp_prefixed_config_keeps_its_comments(self, tmp_path):
        """End to end for one of them, through the real load → save path."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_file(cfg_path, "\u00a0" + IDENTITY_SEED)

        _set_sisyphus(cfg_path)

        after = _read_bytes(cfg_path).decode("utf-8")
        assert after.startswith("\u00a0")
        for comment in IDENTITY_COMMENTS:
            assert comment in after, comment


class TestRestoreLeavesNoEmptyBackupDir:

    def test_bad_name_on_a_never_saved_config(self, tmp_path):
        """`restore` created `.backup/` before checking the name existed, so a typo against a
        config that had never been saved left an empty directory behind."""
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_file(cfg_path, IDENTITY_SEED)
        with pytest.raises(FileNotFoundError):
            restore(cfg_path, "nope.jsonc")
        assert not os.path.exists(str(tmp_path / ".backup"))


class TestCrOnlyCommentInsideTheManagedSpan:
    """The CR fix has to reach BOTH `//` scanners. `_skip_trivia` finds the start of a span and
    `_skip_value` its end; with only the first fixed (diff review, round two), a `//` comment
    inside `agents` on a CR-only file ran the end scanner to EOF, and `render` spliced the new
    value over everything after it — `categories`, the other top-level keys, both closing
    braces — leaving invalid JSON. That placement is what omo's own commented-out palette looks
    like, so it is the common case, not an exotic one."""

    SEED = (
        "// banner\n"
        "{\n"
        '  "team_mode": true,\n'
        '  "[opencode]": {\n'
        '    "agents": {\n'
        '      "sisyphus": {\n'
        '        "model": "opencode/glm-5"\n'
        '        // "model": "openai/gpt-5.5"\n'
        "      }\n"
        "    },\n"
        '    "categories": {"quick": {"model": "opencode/glm-5"}}\n'
        "  },\n"
        '  "claude_code": {"enabled": false}\n'
        "}\n"
    )

    @pytest.mark.parametrize("newline", ["\r", "\r\n", "\n"], ids=["cr", "crlf", "lf"])
    def test_tail_after_the_span_survives(self, tmp_path, newline):
        import json5
        cfg_path = str(tmp_path / "omo.jsonc")
        _write_bytes(cfg_path, self.SEED.replace("\n", newline).encode("utf-8"))

        _set_sisyphus(cfg_path)

        after = _read_bytes(cfg_path).decode("utf-8")
        parsed = json5.loads(after)  # still a document, not a truncated one
        assert parsed["[opencode]"]["agents"]["sisyphus"]["model"] == "opencode/glm-9"
        assert parsed["[opencode]"]["categories"] == {"quick": {"model": "opencode/glm-5"}}
        assert parsed["claude_code"] == {"enabled": False}
        assert parsed["team_mode"] is True
        assert "// banner" in after
        # The file keeps its ending kind throughout, and the end scanner stopped at the span.
        other = {"\r": "\n", "\r\n": None, "\n": "\r"}[newline]
        if other is not None:
            assert other not in after.replace("\r\n", "")
        cfg, resolved = load_config(cfg_path)
        assert save(cfg, resolved).changed is False

    def test_end_scanner_stops_at_a_cr_terminated_comment(self):
        from omodel.config_io import _skip_value
        text = '{ // note\r  "a": 1\r}\rTAIL'
        end = _skip_value(text, 0)
        assert text[end:] == "\rTAIL"
