"""Clean JSONC read / serialize / backups / restore / scaffold.  DESIGN.md §config_io.py.

FROZEN CONTRACT — owned by the Config-I/O specialist. Implement the bodies; keep these
signatures and the SaveResult/BackupInfo shapes (cli.py + app.py depend on them).

⚠ REAL-CONFIG SAFETY: never default-write the user's live config in tests. Every test
passes an explicit temp `path`; the live ~/.config/opencode/oh-my-openagent.jsonc is off-limits.
"""
from __future__ import annotations

import difflib
import glob
import json
import os
import shutil
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


class ConfigParseError(ValueError):
    """Raised by load_config() when the on-disk JSONC fails to parse (malformed syntax).
    The message includes the config path and the underlying json5 error, so callers (cli.py)
    can print a friendly one-liner instead of letting a raw json5 traceback escape."""


def config_path(cli_override: str = None) -> str:
    """Resolve the config path: cli_override, else $XDG_CONFIG_HOME/opencode/oh-my-openagent.jsonc,
    else ~/.config/opencode/oh-my-openagent.jsonc. Does NOT require the file to exist."""
    if cli_override is not None:
        return str(cli_override)
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return str(Path(xdg) / "opencode" / "oh-my-openagent.jsonc")
    return str(Path.home() / ".config" / "opencode" / "oh-my-openagent.jsonc")


def load_config(path: str = None):
    """Resolve via config_path(path); if missing, scaffold the bundled
    data/default-config.jsonc to that location; json5.load → ordered dict.
    Returns (cfg: dict, resolved_path: str). `agents`/`categories` are editable; every
    other top-level key (claude_code, experimental, team_mode, $schema, …) passes through
    by value. Raises ConfigParseError if the on-disk JSONC is malformed."""
    import json5
    import importlib.resources

    resolved = config_path(path)

    if not os.path.exists(resolved):
        # Scaffold from bundled default-config.jsonc
        default_ref = importlib.resources.files("omodel.data") / "default-config.jsonc"
        default_text = default_ref.read_text(encoding="utf-8")
        # dirname() of a bare relative filename (no directory component) is "" — resolve via
        # abspath first so a relative `--config foo.jsonc` doesn't crash makedirs(exist_ok=True).
        os.makedirs(os.path.dirname(os.path.abspath(resolved)), exist_ok=True)
        with open(resolved, "w", encoding="utf-8") as f:
            f.write(default_text)

    with open(resolved, encoding="utf-8") as f:
        try:
            cfg = json5.load(f)
        except ValueError as exc:
            raise ConfigParseError(f"could not parse config at {resolved}: {exc}") from exc

    return cfg, resolved


def _clean_agents(agents: dict) -> dict:
    """Return a COPY of the agents map with empty ultrawork/compaction sub-objects removed
    (an added-but-unfilled sub-target must not persist — clean active-only). Never mutates
    the input; preserves key order."""
    out: dict = {}
    for name, data in agents.items():
        if not isinstance(data, dict):
            out[name] = data
            continue
        cleaned = {}
        for k, v in data.items():
            if k in ("ultrawork", "compaction") and isinstance(v, dict) and not v.get("model"):
                continue  # drop empty / model-less sub-object
            cleaned[k] = v
        out[name] = cleaned
    return out


def serialize(cfg: dict) -> str:
    """EXACT format (DESIGN §config_io serialize):
      (1) ordered dict preserving on-disk key order, but FORCE `$schema` to position 0 if present;
      (2) within agents/categories, freshly-added sub-keys (ultrawork/compaction) APPENDED,
          cleared fields DELETED;
      (3) body = json.dumps(cfg, indent=2, ensure_ascii=False);  json.dumps cannot emit comments;
      (4) return "// Generated by oModel — edit via `omodel`\\n" + body + "\\n" (single trailing \\n)."""
    # (1) Build ordered dict with $schema forced to position 0
    ordered: dict = {}
    if "$schema" in cfg:
        ordered["$schema"] = cfg["$schema"]
    for k, v in cfg.items():
        if k == "$schema":
            continue  # already placed first
        if k == "agents" and isinstance(v, dict):
            ordered[k] = _clean_agents(v)  # drop empty ultrawork/compaction sub-objects
        else:
            ordered[k] = v

    # (3) Serialize — json.dumps preserves insertion order for dicts in Python 3.7+
    body = json.dumps(ordered, indent=2, ensure_ascii=False)

    # (4) Return with header and single trailing newline
    return "// Generated by oModel — edit via `omodel`\n" + body + "\n"


# --- text-preserving render -------------------------------------------------------------
# omodel manages ONLY the top-level `agents` and `categories` objects. `render()` rewrites just
# those two value spans in place and leaves the rest of the file — other keys, formatting, and
# crucially any comments or commented-out config OUTSIDE those two — byte-for-byte intact. The
# commented palette INSIDE agents/categories is still dropped (those spans are rewritten clean;
# decision #13). `serialize()` above stays the canonical clean form (dirtiness + from-scratch
# fallback) and is never required to equal the on-disk bytes.

def _skip_trivia(text: str, j: int) -> int:
    """Advance past JSON whitespace and // line / /* block */ comments; return the new index."""
    n = len(text)
    while j < n:
        c = text[j]
        if c in " \t\r\n":
            j += 1
        elif c == "/" and j + 1 < n and text[j + 1] == "/":
            j += 2
            while j < n and text[j] != "\n":
                j += 1
        elif c == "/" and j + 1 < n and text[j + 1] == "*":
            j += 2
            while j < n and not (text[j] == "*" and j + 1 < n and text[j + 1] == "/"):
                j += 1
            j += 2  # consume the closing */
        else:
            break
    return j


def _read_string(text: str, j: int) -> int:
    """`text[j]` is a string's opening quote; return the index just past the closing quote."""
    n = len(text)
    j += 1
    while j < n:
        c = text[j]
        if c == "\\":
            j += 2
            continue
        if c == '"':
            return j + 1
        j += 1
    return j  # unterminated — best effort


def _skip_value(text: str, j: int) -> int:
    """`text[j]` is the first char of a JSON value; return the index just past that value.
    Objects/arrays are scanned with full string/comment/nesting awareness so a `}` or `"`
    inside a string or comment never ends the scan early."""
    n = len(text)
    c = text[j]
    if c == '"':
        return _read_string(text, j)
    if c in "{[":
        depth = 0
        while j < n:
            c = text[j]
            if c == '"':
                j = _read_string(text, j)
                continue
            if c == "/" and j + 1 < n and text[j + 1] == "/":
                j += 2
                while j < n and text[j] != "\n":
                    j += 1
                continue
            if c == "/" and j + 1 < n and text[j + 1] == "*":
                j += 2
                while j < n and not (text[j] == "*" and j + 1 < n and text[j + 1] == "/"):
                    j += 1
                j += 2
                continue
            if c in "{[":
                depth += 1
            elif c in "}]":
                depth -= 1
                if depth == 0:
                    return j + 1
            j += 1
        return j
    # primitive (number / true / false / null): read to the next delimiter, ws, or comment
    while j < n and text[j] not in ",}]" and text[j] not in " \t\r\n":
        if text[j] == "/" and j + 1 < n and text[j + 1] in "/*":
            break
        j += 1
    return j


def _top_level_value_span(text: str, key: str):
    """Locate `"key": <value>` among the DIRECT members of the root object in JSONC `text`.
    Return (value_start, value_end) of the value, or None if `key` is not a direct root member
    (malformed file, or it only appears nested). Honors strings, comments, and nesting."""
    n = len(text)
    i = _skip_trivia(text, 0)
    if i >= n or text[i] != "{":
        return None
    i += 1  # enter the root object
    while True:
        i = _skip_trivia(text, i)
        if i >= n or text[i] == "}":
            return None
        if text[i] == ",":
            i += 1
            continue
        if text[i] != '"':
            return None  # unexpected token where a member key was expected
        key_start = i
        key_end = _read_string(text, i)
        try:
            this_key = json.loads(text[key_start:key_end])
        except ValueError:
            return None
        i = _skip_trivia(text, key_end)
        if i >= n or text[i] != ":":
            return None
        i = _skip_trivia(text, i + 1)
        if i >= n:
            return None
        value_start = i
        value_end = _skip_value(text, i)
        if this_key == key:
            return (value_start, value_end)
        i = value_end


def _line_indent(text: str, pos: int) -> str:
    """Leading whitespace of the line containing `pos` — used to align a spliced value's
    continuation/closing lines under its key."""
    line_start = text.rfind("\n", 0, pos) + 1
    j = line_start
    while j < len(text) and text[j] in " \t":
        j += 1
    return text[line_start:j]


def _reindent(value_text: str, indent: str) -> str:
    """Prefix `indent` to every line after the first (the first follows `"key": ` inline), so a
    json.dumps(indent=2) block sits correctly under a key at arbitrary depth."""
    lines = value_text.split("\n")
    if len(lines) == 1:
        return value_text
    return lines[0] + "\n" + "\n".join((indent + ln) if ln else ln for ln in lines[1:])


def render(cfg: dict, base_text: str) -> str:
    """Text-preserving serialization. Return `base_text` with ONLY the top-level `agents` and
    `categories` value spans replaced by their clean (comment-free) form; comments, commented-out
    config, other keys, key order, and formatting OUTSIDE those two objects are preserved
    byte-for-byte — omodel manages only those two keys. Falls back to serialize(cfg) when there is
    no base text, or either key is not a direct root member (can't splice safely)."""
    if not base_text or not base_text.strip():
        return serialize(cfg)
    spans = {}
    for key in ("agents", "categories"):
        span = _top_level_value_span(base_text, key)
        if span is None:
            return serialize(cfg)  # non-omo / hand-broken file: degrade to a clean rewrite
        spans[key] = span

    agents_val = cfg.get("agents")
    agents_val = _clean_agents(agents_val) if isinstance(agents_val, dict) else (agents_val or {})
    categories_val = cfg.get("categories")
    categories_val = categories_val if categories_val is not None else {}
    values = {"agents": agents_val, "categories": categories_val}

    result = base_text
    # Splice the later span first so the earlier span's offsets stay valid.
    for key in sorted(spans, key=lambda k: spans[k][0], reverse=True):
        value_start, value_end = spans[key]
        indent = _line_indent(base_text, value_start)
        rendered = _reindent(json.dumps(values[key], indent=2, ensure_ascii=False), indent)
        result = result[:value_start] + rendered + result[value_end:]
    return result


def diff_text(cfg: dict, path: str) -> str:
    """Unified diff of render(cfg, on-disk) vs the current on-disk file (for the confirm modal),
    so the modal shows exactly what changes — agents/categories only, comments outside intact."""
    try:
        with open(path, encoding="utf-8") as f:
            old_text = f.read()
    except FileNotFoundError:
        old_text = ""
    new_text = render(cfg, old_text)

    diff_lines = difflib.unified_diff(
        old_text.splitlines(keepends=True),
        new_text.splitlines(keepends=True),
        fromfile=path,
        tofile=path + " (new)",
    )
    return "".join(diff_lines)


@dataclass
class SaveResult:
    changed: bool
    backup: str = None           # path of timestamped snapshot written this save, or None
    original_created: bool = False  # True iff .backup/original.jsonc was created this save


def save(cfg: dict, path: str) -> SaveResult:
    """No diff → SaveResult(changed=False) ("nothing to save"). Else EXACT order:
      (1) if <dir>/.backup/original.jsonc absent, copy current on-disk config there (verbatim);
      (2) write verbatim timestamped snapshot .backup/YYYYMMDD-HHMMSS[.mmm].jsonc (UTC);
      (3) prune ONLY glob('[0-9]*.jsonc') (EXCLUDES original.jsonc) to the newest 20;
    then atomic temp+rename of render(cfg, on-disk). <dir> = dir of `path`. The write is
    text-preserving: only agents/categories are rewritten; comments / commented-out config
    outside them survive (render() splices in place; missing file → serialize(cfg))."""
    # Check whether anything changed
    try:
        with open(path, encoding="utf-8") as f:
            old_text = f.read()
    except FileNotFoundError:
        old_text = None

    new_text = render(cfg, old_text)

    if old_text is not None and new_text == old_text:
        return SaveResult(changed=False)

    config_dir = os.path.dirname(os.path.abspath(path))
    backup_dir = os.path.join(config_dir, ".backup")
    os.makedirs(backup_dir, exist_ok=True)

    original_path = os.path.join(backup_dir, "original.jsonc")
    original_created = False

    # (1) If original.jsonc absent AND there is an existing on-disk config, pin it verbatim
    if not os.path.exists(original_path) and old_text is not None:
        shutil.copy2(path, original_path)
        original_created = True

    # (2) Write verbatim timestamped snapshot in UTC; .mmm avoids same-second collisions
    now_utc = datetime.now(timezone.utc)
    # Format: YYYYMMDD-HHMMSS.mmm — milliseconds keep lexicographic sort stable
    ts = now_utc.strftime("%Y%m%d-%H%M%S") + f".{now_utc.microsecond // 1000:03d}"
    snapshot_name = f"{ts}.jsonc"
    snapshot_path = os.path.join(backup_dir, snapshot_name)
    if old_text is not None:
        # Verbatim byte copy of the current on-disk file
        shutil.copy2(path, snapshot_path)
    else:
        # Config didn't exist yet — snapshot an empty string so the slot exists
        with open(snapshot_path, "w", encoding="utf-8") as f:
            f.write("")

    # (3) Prune ONLY timestamped snapshots (glob '[0-9]*.jsonc' excludes original.jsonc)
    #     Keep the newest 20.
    timestamped = sorted(
        glob.glob(os.path.join(backup_dir, "[0-9]*.jsonc"))
    )  # lexicographic = chronological thanks to YYYYMMDD-… format
    if len(timestamped) > 20:
        for old_snap in timestamped[:-20]:
            try:
                os.remove(old_snap)
            except OSError:
                pass  # best-effort prune

    # Atomic temp-write + os.replace
    config_parent = os.path.dirname(os.path.abspath(path))
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=config_parent,
        delete=False,
        suffix=".tmp",
    ) as tmp:
        tmp.write(new_text)
        tmp_path = tmp.name
    os.replace(tmp_path, path)

    return SaveResult(changed=True, backup=snapshot_path, original_created=original_created)


@dataclass
class BackupInfo:
    name: str          # filename within .backup/
    path: str
    is_original: bool
    size: int


def list_backups(path: str) -> list:
    """[BackupInfo]: the pinned original.jsonc + the newest 10 timestamped snapshots,
    newest first (DESIGN --restore; items 11–20 are an unlisted on-disk buffer)."""
    config_dir = os.path.dirname(os.path.abspath(path))
    backup_dir = os.path.join(config_dir, ".backup")

    result: list = []

    # Pinned original (if present) — always first
    original_path = os.path.join(backup_dir, "original.jsonc")
    if os.path.exists(original_path):
        result.append(BackupInfo(
            name="original.jsonc",
            path=original_path,
            is_original=True,
            size=os.path.getsize(original_path),
        ))

    # Newest 10 timestamped snapshots, newest first
    timestamped = sorted(
        glob.glob(os.path.join(backup_dir, "[0-9]*.jsonc"))
    )  # lexicographic ascending = chronological; reverse for newest-first
    for snap in reversed(timestamped[-10:]):
        result.append(BackupInfo(
            name=os.path.basename(snap),
            path=snap,
            is_original=False,
            size=os.path.getsize(snap),
        ))

    return result


def restore(path: str, backup_name: str) -> None:
    """Snapshot the CURRENT file first (restore is itself undoable), then copy the chosen
    backup (by `backup_name` within .backup/) to `path`."""
    config_dir = os.path.dirname(os.path.abspath(path))
    backup_dir = os.path.join(config_dir, ".backup")
    os.makedirs(backup_dir, exist_ok=True)

    # Snapshot the current live config first (so the restore itself is undoable)
    now_utc = datetime.now(timezone.utc)
    ts = now_utc.strftime("%Y%m%d-%H%M%S") + f".{now_utc.microsecond // 1000:03d}"
    snapshot_path = os.path.join(backup_dir, f"{ts}.jsonc")
    if os.path.exists(path):
        shutil.copy2(path, snapshot_path)
    else:
        # Nothing to snapshot; create an empty slot so the restore slot is still tracked
        with open(snapshot_path, "w", encoding="utf-8") as f:
            f.write("")

    # Copy the chosen backup verbatim to the live config path. Sanitize backup_name to a
    # bare basename so it cannot escape .backup/ (path traversal), and require it to exist.
    safe_name = os.path.basename(backup_name)
    src = os.path.join(backup_dir, safe_name)
    if not os.path.isfile(src):
        raise FileNotFoundError(f"backup not found: {safe_name}")
    shutil.copy2(src, path)
