"""Clean JSONC read / serialize / backups / restore / scaffold.  DESIGN.md §config_io.py.

FROZEN CONTRACT — owned by the Config-I/O specialist. Implement the bodies; keep these
signatures and the SaveResult/BackupInfo shapes (cli.py + app.py depend on them).

⚠ REAL-CONFIG SAFETY: never default-write the user's live config in tests. Every test
passes an explicit temp `path`; the live ~/.config/opencode/oh-my-openagent.jsonc is off-limits.
"""
from __future__ import annotations

from dataclasses import dataclass


def config_path(cli_override: str = None) -> str:
    """Resolve the config path: cli_override, else $XDG_CONFIG_HOME/opencode/oh-my-openagent.jsonc,
    else ~/.config/opencode/oh-my-openagent.jsonc. Does NOT require the file to exist."""
    raise NotImplementedError


def load_config(path: str = None):
    """Resolve via config_path(path); if missing, scaffold the bundled
    data/default-config.jsonc to that location; json5.load → ordered dict.
    Returns (cfg: dict, resolved_path: str). `agents`/`categories` are editable; every
    other top-level key (claude_code, experimental, team_mode, $schema, …) passes through
    by value."""
    raise NotImplementedError


def serialize(cfg: dict) -> str:
    """EXACT format (DESIGN §config_io serialize):
      (1) ordered dict preserving on-disk key order, but FORCE `$schema` to position 0 if present;
      (2) within agents/categories, freshly-added sub-keys (ultrawork/compaction) APPENDED,
          cleared fields DELETED;
      (3) body = json.dumps(cfg, indent=2, ensure_ascii=False);  json.dumps cannot emit comments;
      (4) return "// Generated by oModel — edit via `omodel`\\n" + body + "\\n" (single trailing \\n)."""
    raise NotImplementedError


def diff_text(cfg: dict, path: str) -> str:
    """Unified diff of serialize(cfg) vs the current on-disk file (for the confirm modal)."""
    raise NotImplementedError


@dataclass
class SaveResult:
    changed: bool
    backup: str = None           # path of timestamped snapshot written this save, or None
    original_created: bool = False  # True iff .backup/original.jsonc was created this save


def save(cfg: dict, path: str) -> SaveResult:
    """No diff → SaveResult(changed=False) ("nothing to save"). Else EXACT order:
      (1) if <dir>/.backup/original.jsonc absent, copy current on-disk config there (verbatim);
      (2) write verbatim timestamped snapshot .backup/YYYYMMDD-HHMMSS[.mmm].jsonc (UTC);
      (3) prune ONLY glob('[0-9]*.jsonc') (EXCLUDES original.jsonc) to the newest 20;
    then atomic temp+rename of serialize(cfg). <dir> = dir of `path`."""
    raise NotImplementedError


@dataclass
class BackupInfo:
    name: str          # filename within .backup/
    path: str
    is_original: bool
    size: int


def list_backups(path: str) -> list:
    """[BackupInfo]: the pinned original.jsonc + the newest 10 timestamped snapshots,
    newest first (DESIGN --restore; items 11–20 are an unlisted on-disk buffer)."""
    raise NotImplementedError


def restore(path: str, backup_name: str) -> None:
    """Snapshot the CURRENT file first (restore is itself undoable), then copy the chosen
    backup (by `backup_name` within .backup/) to `path`."""
    raise NotImplementedError
